Graphql changes for new labels schema
hypertrace/hypertrace-graphql pull request #113
Opened 2021-11-08 12:45 UTC by kamaleshnneerasa

## Description
Please include a summary of the change, motivation and context.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### Documentation
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

2021-11-08 15:25 UTC, aaron-steinfeld commented on hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/schema/mutation/LabelMutationSchema.java
> +  Label updateLabel(@GraphQLNonNull @GraphQLName(UpdateLabel.ARGUMENT_NAME) UpdateLabel label);
nit: match code arg names to declared arg names
```suggestion
  Label updateLabel(@GraphQLNonNull @GraphQLName(UpdateLabel.ARGUMENT_NAME) UpdateLabel updateLabel);
```

(same for create)

2021-11-08 15:25 UTC, aaron-steinfeld commented on hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/schema/query/Label.java
> +  @GraphQLNonNull
This field is optional, so should be nullable

2021-11-08 15:25 UTC, aaron-steinfeld commented on hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/schema/mutation/CreateLabel.java
> +  String CREATED_BY_RULE_ID_KEY = "createdByRuleId";
This is only for internally created rules, need not expose on the API for write

2021-11-08 15:25 UTC, aaron-steinfeld commented on hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/dao/LabelResponseConverter.java
> +    static final LabelResultSet EMPTY_LABEL_RESULT_SET =
Is this ever used?

2021-11-09 05:16 UTC, kamaleshnneerasa commented on hypertrace-graphql-labels-schema/src/main/java/org/hypertrace/graphql/label/dao/LabelResponseConverter.java
> +    static final LabelResultSet EMPTY_LABEL_RESULT_SET =
I think it is used in joiner.

2021-11-09 13:05 UTC, aaron-steinfeld reviewed
Please revert the submodule change - this PR is rolling back the submodules several months  (from `f50dca8` to `2edb271`)

2021-11-09 13:08 UTC, aaron-steinfeld requested changes
Sorry for just picking up on this, but the GQL changes were only meant to be in the GQL<-> config service adapter - that is, the DAO.

Changing the GQL schema here will break the UI, which we can't do.

2021-11-11 18:10 UTC, closed without merging